---

- import_tasks: helm.yml
  vars:
    namespace: meals-planner
    meals_release: meals-release
    planner_release: planner-release
  tags: deploy.helm

- import_tasks: kubectl.yml
  tags: deploy.kubectl

...
