---

# Playbook to bring infrastructure and setup k8s cluster

- hosts: all
  gather_facts: True
  become: yes
  roles:
    - common
  tags: common

- hosts: worker_nodes
  gather_facts: True
  become: yes
  roles:
    - setup
  tags: setup
...
