---

# Installing docker, kubelet, kubeadm, kubectl on al nodes
- hosts: all
  gather_facts: True
  become: yes
  roles:
    - role: common
      tags: setup

# creating k8s cluster and deploying the app
- hosts: master_node
  gather_facts: True
  # become: yes
  roles:
    - k8s
    - role: deploy
      tags: deploy

...
