---

# Playbook to bring infrastructure and setup k8s cluster

- hosts: all
  gather_facts: True
  become: yes
  become_user: root 
  roles:
    - common
  tags:
    - common

- hosts: app_nodes
  gather_facts: True
  become: yes
  become_user: root 
  roles:
    - setup
  tags:
    - setup
...
