---

# Playbook to bring infrastructure and setup k8s cluster

- hosts: all
  gather_facts: True
  become: yes
  roles:
    - common
  tags: common

- hosts: 127.0.0.1
  connection: local
  gather_facts: True
  become: yes
  roles:
    - deploy
  tags: deploy

- hosts: worker_nodes
  gather_facts: True
  become: yes
  roles:
    - setup
  tags: setup
...
