kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.database.host }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
    tier: {{ .Values.database.labels.tier }}
    version: {{ .Values.database.labels.version }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}