---

- name: delete existing minikube cluster for clean-up
  shell: minikube delete
  ignore_errors: True

- name: delete kubeadm files
  shell: kubeadm reset

- name: start minikube with a new k8s cluster
  shell: minikube start --vm-driver=none

...
