---

# Installing kubeadm

#- name: Run the equivalent of "apt-get update" as a separate step
#  apt:
#    update_cache: yes
#  tags: k8s
#
#- name: Upgrade all packages to the latest version
#  apt:
#    name: "*"
#    state: latest
#    force_apt_get: True
#  tags: k8s

- name: Install the package "apt-transport-https"
  apt:
    name: apt-transport-https
    state: present

- name: add the key to the repo
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

- name: add the k8s repository 
  shell: "{{ item }}"
  loop:
    - touch /etc/apt/sources.list.d/kubernetes.list
    - echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install the packages "kubelet, kubeadm, kubectl"
#  apt:
#    name: "{{ item }}" 
#    state: present
  shell: apt-get install {{ item }} -y --allow-downgrades
  loop:
    - kubelet #=1.8.3-00
    - kubeadm #=1.8.3-00
    - kubectl #=1.8.3-00

- name: disable the swaps on worker nodes
  shell: sudo swapoff -a

- name: Remove the packages kubelet, kubeadm, & kubectl
  block:
    - name: remove all the packages
      apt:
        name: "{{ item }}" 
        state: absent 
      loop:
        - kubelet
        - kubeadm
        - kubectl
    - name: clean the cache
      apt:
        autoclean: yes
    - name: apt autoremove the packages
      apt:
        autoremove: yes
  tags: k8s.delete

...
