---

# Installing kubeadm

#- name: Run the equivalent of "apt-get update" as a separate step
#  apt:
#    update_cache: yes
#  tags: k8s
#
#- name: Upgrade all packages to the latest version
#  apt:
#    name: "*"
#    state: latest
#    force_apt_get: True
#  tags: k8s

- name: Install the package "apt-transport-https"
  apt:
    name: apt-transport-https
    state: present
  tags: k8s

- name: add the key to the repo
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  tags: k8s

- name: add the k8s repository 
  shell: "{{ item }}"
  loop:
    - touch /etc/apt/sources.list.d/kubernetes.list
    - echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  tags: k8s

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  tags: k8s

- name: Install the packages "kubelet, kubeadm, kubectl"
#  apt:
#    name: "{{ item }}" 
#    state: present
  shell: apt-get install {{ item }} -y --allow-downgrades
  loop:
    - kubelet=1.8.3-00
    - kubeadm=1.8.3-00
    - kubectl=1.8.3-00
  tags: k8s

- name: disable the swaps on worker nodes
  shell: sudo swapoff -a
  tags: k8s

- name: reset all kubeadm installed state
  shell: kubeadm reset
  tags: k8s

- name: create k8s cluster on master node
  block: 
    - name: initialize master node
      shell: kubeadm init --config /home/django/Development/infrastructure/kubeadm.yaml
      register: result  
    - debug: msg={{ result.stdout_lines }}

    - name: create .kube folder
      shell: mkdir -p $HOME/.kube 
      become_user: django

    - name: create kube config file
      shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

    - name: changing the owner of the kube config
      shell: chown $(id -u):$(id -g) $HOME/.kube/config

    - name: make kube-proxy multiplatform
      shell: kubectl -n kube-system set image daemonset/kube-proxy kube-proxy=luxas/kube-proxy:v1.8.0
      become_user: django

    - name: deploy pod networking plugin. Install kubernetes networking extension called Weave Net.
      shell: kubectl apply -f https://git.io/weave-kube-1.6
      become_user: django
  when: inventory_hostname is search('django-laptop')
  tags: k8s

#- name: join the worker nodes
#  shell: 
#  when: inventory_hostname is not search('django-laptop')
#  tags: k8s

- name: Remove the packages kubelet, kubeadm, & kubectl
  block:
    - name: remove all the packages
      apt:
        name: "{{ item }}" 
        state: absent 
      loop:
        - kubelet
        - kubeadm
        - kubectl
    - name: clean the cache
      apt:
        autoclean: yes
    - name: apt autoremove the packages
      apt:
        autoremove: yes
  tags: k8s.delete

...
