---

- name: get the docker repository key for odroid
  shell: "{{ item }}"
  loop:
    - apt-get update
    - apt-get install apt-transport-https ca-certificates curl software-properties-common -y
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - apt-key fingerprint 0EBFCD88
  when: delete is not defined

- name: add docker repository for odroid
  shell: add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  when: delete is not defined

- name: install docker-ce for odroid
  apt:
    name: docker-ce=17.09.0~ce-0~ubuntu
    state: present
  when: delete is not defined

#- name: Run the equivalent of "apt-get update" as a separate step
#  apt:
#    update_cache: yes

#  shell: "{{ item }}"
#  loop:
#    - apt-get update
#    - apt-get install docker-ce 

- name: check if docker is running
  shell: systemctl status docker
  register: result
  when: delete is not defined

- debug: msg="{{ result.stdout_lines }}"
  when: delete is not defined

- name: uninstall docker-ce
  apt:
    name: docker-ce
    state: absent
  when: delete is defined
  tags: [setup.pi.delete]

...
